name: CI
on:
  push:
    branches:
      - master
jobs:
  shared:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.2
      - run: npm ci
      - run: npx vitest run

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.2
      - run: npm ci
      - working-directory: frontend
        run: npm run test:unit
      - working-directory: frontend
        run: |
          npx tsc -b
          npx vite build

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.2
      - run: npm ci
      - working-directory: backend
        run: npm run test:unit
      - working-directory: frontend
        run: |
          npx tsc -b
          npx vite build
